### ISSUE TITLE
opening About box locks up UI and prevents use of Refresh and Quit

### ISSUE THREAD

**Issue by idallen** [gregkh/usbview#22]
What's your reasoning in preventing me from using `Refresh` or `Quit` if the `About` box is open?

Is there some UI consequence I don't understand?

I happened to have opened the `About` box, then got distracted by other things that ended up covering up the box, and when I went back the next day to try to `Quit` `usbview`, it wouldn't let me.  I had to dig around to find the open `About` box and close it first.  I couldn't even click on the `About` button to toggle the box closed; I had to actually find the box and use `Close`.  Can this be made easier?

**Comment by gregkh** [comment]
This is because the About box is a child of the main program window.  It's always been this way, I could change it, but why keep the About window open for longer than just a few seconds anyway?

**Comment by gregkh** [comment]
This has traditionally been the way "About" dialog boxes work, in a modal way, blocking the rest of the program.

This program has been working like this since 1999 when it was first released, so to change it now, all these years later, might be a bit odd.

So I'm going to leave it as-is for now, thanks.
